shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home_page, header, footer

urlpatterns = [
    path('', home_page),
    path('header', header, name='header'),
    path('footer', footer, name='footer'),
    path('', include('shopaccount.urls')),
    path('', include('shopproducts.urls')),
    path('', include('shopcontact.urls')),
    path('', include('shoporder.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopproducts/urls.py
from django.urls import path
from .views import (ProductsList, ProductListByCategory,
                    product_detail, SearchProductView,
                    products_categories_partial,)

urlpatterns = [
    path('products', ProductsList.as_view()),
    path('products/<productId>/<title>', product_detail),
    path('products/search', SearchProductView.as_view()),
    path('products/<category_name>', ProductListByCategory.as_view()),
    path('products_categories_partial', products_categories_partial, name='products_categories_partial'),

]

shopproducts/models.py
from django.db.models import Q
from django.db import models
from shopcategory.models import ProductCategory


# Create your models here.


class ProductManager(models.Manager):

    def get_active_product(self):
        return self.get_queryset().filter(active=True)

    def get_by_category(self, category_name):
        return self.get_queryset().filter(categories__name__iexact=category_name, active=True)

    def get_by_id(self, product_id):
        qs = self.get_queryset().filter(pk=product_id)
        if qs.count() == 1:
            return qs.first()
        else:
            return None

    def search(self, query):
        lookup = (Q(title__icontains=query) |
                  Q(description__icontains=query) |
                  Q(tag__title__icontains=query)
                  )

        return self.get_queryset().filter(lookup, active=True).distinct()


class Products(models.Model):
    title = models.CharField(max_length=60, verbose_name='عنوان')
    description = models.TextField(verbose_name='توضیحات')
    price = models.IntegerField(verbose_name='قیمت')
    image = models.ImageField(upload_to='products/', blank=True, null=True, verbose_name='تصویر')
    active = models.BooleanField(default=True, verbose_name='فعال/غیرفعال')
    categories = models.ManyToManyField(ProductCategory, blank=True, verbose_name='دسته بندی')
    visit_count = models.IntegerField(default=0 , verbose_name='تعداد بازدید')

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'


    def __str__(self):
        return self.title

    objects = ProductManager()

    def get_absolute_url(self):
        return f"/products/{self.pk}/{self.title.replace(' ', '-')}"


class Gallery(models.Model):
    title = models.CharField(max_length=100, verbose_name='عنوان')
    image = models.ImageField(upload_to='products/gallery', verbose_name='تصویر')
    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name='محصول')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'تصویر'
        verbose_name_plural = 'تصاویر'

shopproducts/views.py
import itertools

from django.shortcuts import render
from django.views.generic import ListView, DetailView

from shopcategory.models import ProductCategory
from shoporder.forms import UserNewOrderForm
from shoptags.models import Tag
from .models import Products, Gallery
from django.http import Http404


# Create your views here.

class ProductsList(ListView):
    template_name = 'products/products_list.html'
    paginate_by = 6

    # def get_queryset(self):
    #     return Products.objects.get_queryset().filter(active=True)
    queryset = Products.objects.get_active_product()


# class ProductsDetail(DetailView):
#     template_name = 'products/products_detail.html'
#     queryset = Products.objects.all()

class ProductListByCategory(ListView):
    template_name = 'products/products_list.html'
    paginate_by = 6

    def get_queryset(self):
        category_name = self.kwargs['category_name']
        category = ProductCategory.objects.filter(name__iexact=category_name).first()
        if category is None:
            raise Http404('صفحه مورد نظر یافت نشد')
        return Products.objects.get_by_category(category_name)


def my_grouper(n, iterable):
    args = [iter(iterable)] * n
    return ([e for e in t if e is not None] for t in itertools.zip_longest(*args))


def product_detail(request, *args, **kwargs):
    # getting product for detail
    product_id = kwargs['productId']
    new_order_form = UserNewOrderForm(request.POST or None, initial={'product_id': product_id})
    product : Products = Products.objects.get_by_id(product_id)

    product.visit_count += 1
    product.save()
    # galleries picture
    galleries = Gallery.objects.filter(product_id=product_id)
    grouped_galleries = list(my_grouper(3, galleries))

    # related products
    related_products = Products.objects.filter(categories__products=product).distinct()
    grouped_related_products = list(my_grouper(3, related_products))

    context = {
        'product': product,
        'grouped_galleries': grouped_galleries,
        'grouped_related_products': grouped_related_products,
        'new_order_form': new_order_form
    }
    #
    # tags = Tag.objects.filter(title__icontains='django').first()
    # print(tags.products.all())

    if product is None or not product.active:
        raise Http404
    else:
        return render(request, 'products/products_detail.html', context)


class SearchProductView(ListView):
    template_name = 'products/products_list.html'

    def get_queryset(self):
        request = self.request
        query = request.GET.get('q')
        if query is not None:
            return Products.objects.search(query)
        return Products.objects.get_active_product()

    paginate_by = 6


def products_categories_partial(request):
    categories = ProductCategory.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'products/products_categories_partial.html', context)

shopproducts/templates/products/product_item_component.html
<div class="col-sm-4 pull-right">
    <div class="product-image-wrapper">
        <div class="single-products">
            <div class="productinfo text-center">
                <img src="{{ product.image.url }}" alt="">
                <h2>{{ product.price }} هزار تومان</h2>
                <p>توضیحات کوتـاه محصـول</p>
                <a href="#" class="btn btn-default add-to-cart"><i
                        class="fa fa-shopping-cart"></i>افزودن به سبـد خریـد</a>
            </div>
            <a href="{{ product.get_absolute_url }}">
                <div class="product-overlay">
                    <div class="overlay-content">
                        <h2>{{ product.price }} هزار تومان</h2>
                        <p>توضیحات کوتـاه محصـول</p>
                        <a href="#" class="btn btn-default add-to-cart"><i
                                class="fa fa-shopping-cart"></i>افزودن به سبـد خریـد
                        </a>
                    </div>
                </div>
            </a>
        </div>
        <div class="choose">
            <ul class="nav nav-pills nav-justified">
                <li><a href="{{ product.get_absolute_url }}"><i class="fa fa-plus-square"></i>مشاهده محصول</a></li>
                <li><a href=""><i class="fa fa-plus-square"></i>مقایسه</a></li>
            </ul>
        </div>
    </div>
</div>

shopproducts/templates/products/products_categories_partial.html
<div class="panel-group category-products" id="accordian"><!--category-productsr-->
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title"><a href="/products">همه</a></h4>
        </div>
    </div>
    {% for category in categories %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><a href="/products/{{ category.name }}">{{ category.title }}</a></h4>
            </div>
        </div>

    {% endfor %}


</div>

shopproducts/templates/products/products_detail.html
{% extends 'shared/_MainLayout.html' %}
{% load static %}
{% load render_partial %}

{% block content %}

    <section>
        <div class="container">
            <div class="row">

                <div class="col-sm-9 padding-right">
                    <div class="product-details"><!--product-details-->
                        <div class="col-sm-5">
                            <div class="view-product">
                                <img src="{{ product.image.url }}" alt="">
                                <h3>بزرگنمایـی</h3>
                            </div>
                            <div id="similar-product" class="carousel slide" data-ride="carousel">

                                <!-- Wrapper for slides -->
                                <div class="carousel-inner">
                                    {% for gallery_list in grouped_galleries %}
                                        <div class="item {{ forloop.first|yesno:'active,' }}">
                                            {% for gallery_item in gallery_list %}
                                                <a href=""><img src="{{ gallery_item.image.url }}"
                                                                alt="{{ gallery_item.title }}"
                                                                style="width: 85px;height: 85px;">
                                                </a>
                                            {% endfor %}

                                        </div>
                                    {% endfor %}


                                </div>

                                <!-- Controls -->
                                <a class="right item-control" href="#similar-product" data-slide="next">
                                    <i class="fa fa-angle-right"></i>
                                </a>
                                <a class="left item-control" href="#similar-product" data-slide="prev">
                                    <i class="fa fa-angle-left"></i>
                                </a>
                            </div>

                        </div>
                        <div class="col-sm-7">
                            <div class="product-information"><!--/product-information-->
                                <img src="{% static 'images/product-details/new.png' %}" class="newarrival" alt="">
                                <div>
                                    <h2>{{ product.title }}</h2>
                                    <h2>کـالای شمـاره {{ product.pk }}</h2>
                                    <p>شناسـه : {{ product.product_id }}</p>
                                </div>
                                <div>
									<span>
										<span>قیمت : {{ product.price }} تومان</span>
									</span>
                                    <span>
                                        <form action="/order" method="post">
                                            {% csrf_token %}
                                            {{ new_order_form.product_id }}
										<label>تعداد :</label>
                                            {{ new_order_form.count }}
										<button type="submit" class="btn btn-fefault cart">
											<i class="fa fa-shopping-cart"></i>
											افـزودن به سبـد خریـد
										</button>
                                            </form>
									</span>
                                </div>
                                <div>
                                    <p><b>موجـودی :</b> در انبـار موجود می باشد</p>
                                    <p><b>شرایـط :</b> جدیـد</p>
                                    <p><b>برنـد :</b> برنـد </p>
                                </div>
                                <span class="socials-share share">
									<ul>
										<a href="#">
											<li>
												<label>بلـه</label>
												<img src="{% static 'images/product-details/Bale.png' %}">
											</li>
										</a>
										<a href="#">
											<li>
												<label>سـروش</label>
												<img src="{% static 'images/product-details/Soroush.png' %}">
											</li>
										</a>
										<a href="#">
											<li>
												<label>اینستاگرام</label>
												<img src="{% static 'images/product-details/Instagram.png' %}">
											</li>
										</a>
										<li><img src="{% static 'images/product-details/rating.png' %}" alt=""></li>
									</ul>
								</span>

                            </div><!--/product-information-->
                        </div>
                    </div><!--/product-details-->

                    <div class="category-tab shop-details-tab"><!--category-tab-->
                        <div class="col-sm-12">
                            <ul class="nav nav-tabs">
                                <li><a href="#details" data-toggle="tab">جزئیات</a></li>
                                <li><a href="#companyprofile" data-toggle="tab">درباره سازنده</a></li>
                                <li><a href="#tag" data-toggle="tab">برچسب</a></li>
                                <li class="active"><a href="#reviews" data-toggle="tab">نظرات (5)</a></li>
                            </ul>
                        </div>
                        <div class="tab-content">
                            <div class="tab-pane fade" id="details">
                                <div class="col-md-12">
                                    <p>
                                        {{ product.description }}
                                    </p>
                                </div>
                            </div>

                            <div class="tab-pane fade" id="companyprofile">
                                <div class="col-sm-3">
                                    <div class="product-image-wrapper">
                                        <div class="single-products">
                                            <div class="productinfo text-center">
                                                <img src="{% static 'images/home/gallery.jpg' %}" alt="">
                                                <h2>1.250.000 ريال</h2>
                                                <p>توضیحات کوتاه محصول</p>
                                                <button type="button" class="btn btn-default add-to-cart"><i
                                                        class="fa fa-shopping-cart"></i>افزودن به سبـد خریـد
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="product-image-wrapper">
                                        <div class="single-products">
                                            <div class="productinfo text-center">
                                                <img src="{% static 'images/home/gallery.jpg' %}" alt="">
                                                <h2>1.250.000 ريال</h2>
                                                <p>توضیحات کوتاه محصول</p>
                                                <button type="button" class="btn btn-default add-to-cart"><i
                                                        class="fa fa-shopping-cart"></i>افزودن به سبـد خریـد
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="product-image-wrapper">
                                        <div class="single-products">
                                            <div class="productinfo text-center">
                                                <img src="{% static 'images/home/gallery.jpg' %}" alt="">
                                                <h2>1.250.000 ريال</h2>
                                                <p>توضیحات کوتاه محصول</p>
                                                <button type="button" class="btn btn-default add-to-cart"><i
                                                        class="fa fa-shopping-cart"></i>افزودن به سبـد خریـد
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="product-image-wrapper">
                                        <div class="single-products">
                                            <div class="productinfo text-center">
                                                <img src="{% static 'images/home/gallery.jpg' %}" alt="">
                                                <h2>1.250.000 ريال</h2>
                                                <p>توضیحات کوتاه محصول</p>
                                                <button type="button" class="btn btn-default add-to-cart"><i
                                                        class="fa fa-shopping-cart"></i>افزودن به سبـد خریـد
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="tab-pane fade active in" id="reviews">
                                <div class="col-sm-12">
                                    <ul>
                                        <li><a href=""><i class="fa fa-user"></i>مشتـری 1</a></li>
                                        <li><a href=""><i class="fa fa-clock-o"></i>12:41 ب . ظ</a></li>
                                        <li><a href=""><i class="fa fa-calendar-o"></i>29 تیـر 1397</a></li>
                                    </ul>
                                    <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده ازلورملورم
                                        ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان
                                        گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و
                                        برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای
                                        کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان
                                        جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه
                                        ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد.</p>
                                    <p><b>نظـر خود را بنویسیـد</b></p>

                                    <form action="#">
										<span>
											<input type="text" placeholder="نام و نام خانوادگـی">
											<input type="email" placeholder="آدرس ایمیـل">
										</span>
                                        <textarea name=""></textarea>
                                        <b>رتبـه : </b> <img src="{% static 'images/product-details/rating.png' %}"
                                                             alt="">
                                        <button type="button" class="btn btn-default pull-left">
                                            ارسـال
                                        </button>
                                    </form>
                                </div>
                            </div>

                        </div>
                    </div><!--/category-tab-->

                    <div class="recommended_items"><!--recommended_items-->
                        <h2 class="title text-center">محصولات پیشنهادی</h2>

                        <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                {% for grouped_related_product_list in grouped_related_products %}
                                    <div class="item {{ forloop.first|yesno:'active,' }}">
                                        {% for products in grouped_related_product_list %}
                                            {% include 'products/product_item_component.html' with product=products %}
                                        {% endfor %}

                                    </div>
                                {% endfor %}

                            </div>
                            <a class="left recommended-item-control" href="#recommended-item-carousel"
                               data-slide="prev">
                                <i class="fa fa-angle-left"></i>
                            </a>
                            <a class="right recommended-item-control" href="#recommended-item-carousel"
                               data-slide="next">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>
                    </div><!--/recommended_items-->

                </div>

                <div class="col-sm-3">
                    <div class="left-sidebar">
                        <h2>دسته بندی محصولات</h2>
                        {% render_partial 'products_categories_partial' %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

shopproducts/templates/products/products_list.html
{% extends 'shared/_MainLayout.html' %}
{% load static %}
{% load render_partial %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">

                <div class="col-sm-9 padding-right">
                    <div class="features_items"><!--features_items-->
                        <h2 class="title text-center">محصولات</h2>
                        {% for product in page_obj %}
                            {% include 'products/product_item_component.html' with product=product %}
                        {% endfor %}
                        <div class="clearfix"></div>
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">قبلی</a></li>

                            {% endif %}
                            {% for page in paginator.page_range %}
                                {% if page == page_obj.number %}
                                    <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                                {% else %}
                                    <li><a href="?page={{ page }}">{{ page }}</a></li>
                                {% endif %}
                            {% endfor %}



                            {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number }}">بعدی</a></li>

                            {% endif %}
                        </ul>
                    </div><!--features_items-->
                </div>

                <div class="col-sm-3">
                    <div class="left-sidebar">
                        <h2>دسته بندی محصولات</h2>
                        {% render_partial 'products_categories_partial' %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}